### ISSUE TITLE
[feat] supporting save with updating modified data in metadata

### ISSUE THREAD

**Issue by edonyzpc** [edonyzpc/personal-assistant#54]
### Requirement/Scenario
Each note in Obsidian sets its metadata with Templater plugin, the metadata is as following:
```yaml
---

title: <% tp.file.title %>
date: <% tp.file.creation_date("YYYY-MM-DD HH:mm:ss") %>
modify: <% tp.file.last_modified_date("YYYY-MM-DD HH:mm:ss") %>
author: edony.zpc
aliases: [  ]
tags: [  ]

---
%%
subject: #001-computer-technology
status: 
type: 
%%
# <% tp.file.title %>


## References
1. 
```

The `modify` field needs to be updates when save the note.

## Tasks
- [ ] update modify field with current date
- [ ] binding the function to `CMD/Ctrl + s`
